### ISSUE TITLE
Panel icons cramped together during startup time

### ISSUE THREAD

**Issue by baimafeima** [solus-project/budgie-desktop#1113]
**Operating System:** Solus 3
**Budgie version:** Budgie 10.4

**The issue encountered**

Within the first seconds of starting the operating system the icons in the panel are cramped together and then extend during the budgie panel loading process. I don't remember this being an issue in the past.

**Comment by KloudKoder** [comment]
I just saw this report. It sounds like what I discovered as well. I waste so much time rebooting due to this bug, and other bugs which appear to be related (but might not be). We both reported the issue in August, so it sounds like this might be due to one particular code change.

https://github.com/budgie-desktop/budgie-desktop/issues/1082

**Comment by JoshStrobl** [comment]
This is an intentional animation.
