### ISSUE TITLE
Inconsistent intelligent panel hiding with maximized windows

### ISSUE THREAD

**Issue by dar-irl** [solus-project/budgie-desktop#1252]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4

**The issue encountered**
Often times, the panel won't rehide itself after closing a maximized window and switching to a different maximized window, resulting in the panel taking up space on the new window. 

**Steps to reproduce the issue**

1. Set Budgie panel to intelligent auto-hiding
2. Open two windows and maximize them both, with one behind the other (i.e. Terminal)
3. The panel should be hidden as expected. Now, close one of the maximized windows
4. The panel then appears and overlays above the remaining maximized window. Clicking the new window does not cause the panel to re-hide.

![issue](https://user-images.githubusercontent.com/18043024/32959585-03c8a058-cb90-11e7-8fb2-c2bb060b0c57.gif)

**Comment by Snuggle** [comment]
I’ve encountered this before. It annoyed me so much that I’ve started using “Automatic” instead of “Intelligent”. I hope a fix can come soon!

**Comment by K4rloss** [comment]
Just noting the bug is still there

**Comment by xulongwu4** [comment]
I found this issue is not completely fixed. The video posted in #1607 showed that the panel is correctly hidden when switching between two maximized terminal windows. However, if I have a maximized Firefox window and a maximized terminal window, the behaviour is still inconsistent. If I switch from the terminal window to the Firefox window (both maximized), the bottom panel is correctly hidden. However, if I switch from the Firefox window to the terminal window, the bottom panel often pops out even if the terminal window is maximized. This inconsistency is shown is the following gif. I am using the latest Solus when recording this gif.

![Peek 2019-12-02 13-31](https://user-images.githubusercontent.com/16892446/69985334-f86c7300-1508-11ea-91d2-d5e96d4da96c.gif)

**Comment by cata0309** [comment]
Yes, that you are right, I am using Solus 4.1 and the bug is still happening

**Comment by desyncr** [comment]
+1 has similar issue with to panel and autohide.
