### ISSUE TITLE
Some notification pop-ups are very large and should be clamped to a reasonable height

### ISSUE THREAD

**Issue by arcooke** [solus-project/budgie-desktop#1267]
**Operating System**: Solus 3.26.2
**Budgie version**: 10.4

**The issue encountered**

Some notifications are very large and take up the entire vertical screen space, extending well below the bottom of the screen in some cases.  

Below screenshot is an email notification triggered from the Pushbullet extension in Firefox.  HTML emails will show the underlying markup in the notification, so it's common for these pop-ups to be huge. 

![](https://i.imgur.com/qAKaPo7.png)

(The circled area is reported separately in #1266)

**Steps to reproduce the issue**

There are other ways to do this, but this is how things are set up on my end.  Not sure off-hand how to reproduce using simpler methods

* Disable pop-up notifications in gnome control center
* Install Firefox (I'm using nightly, 59.0a1)
* Install Pushbullet extension, sign in
* Install Pushbullet on mobile (I use Android), sign in
* Send yourself an email, wait for mobile notification to come through.

**Comment by Gnat008** [comment]
Would this be a theme change, or a change elsewhere?

**Comment by JoshStrobl** [comment]
@EbonJaeger This would likely be us limiting the character count and/or using the `ellipsize` property like we do on the title. In the case of `NotificationWindow`, since it uses a `.ui` file, it may be best to use Glade and modify the "ellipsize" value of `label_body` under "Formatting" and specify it to End

**Comment by EbonJaeger** [comment]
@JoshStrobl Yeah I was thinking that it would require both a char limit and the `ellipsize` option together. Since this is marked as beginner friendly (and I watched the Hackfest so I know a little how the notification system works :P ), I wouldn't mind poking around with this. Is there anything other than `NotificationWindow` that needs to be looked at?

**Comment by JoshStrobl** [comment]
@EbonJaeger Nope, we already do ellipsizing on `NotificationClone`, only `NotificationWindow` should be necessary :slightly_smiling_face:

**Comment by EbonJaeger** [comment]
@JoshStrobl Sounds good! I'd like to keep changes consistent with the rest of the code, so would you rather the ui be edited in Glade, or have it done in Vala in the `set_from_notify` function?

**Comment by JoshStrobl** [comment]
@EbonJaeger Depends on what you're trying to accomplish. For char limiting, likely `set_from_notify`. Ellipsize should be the .ui file though.
