### ISSUE TITLE
[Budgie Settings] Applets list shows applets descriptions instead of titles

### ISSUE THREAD

**Issue by nextgensparx** [solus-project/budgie-desktop#1301]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4

**The issue encountered**

The applets list in Budgie Settings shows applets descriptions instead of titles. When viewing them in the applet chooser, their titles and descriptions are correctly shown.

**Steps to reproduce the issue**

Go to Budgie Settings and add a new applet to a panel.

**Notes**

It seems that most of the built-in applets' descriptions have been changed to match their titles. Does that mean this issue is known but unfixable?

**Comment by Jacob-Vlijm** [comment]
The .plugin file includes the two fields; Name and Description. In the list to add a new applet, both the title and description is shown. In the list of currently used ones, only the description is used. It depends on the author of the applet if this is used correctly or not, but this is by design we may assume.
