### ISSUE TITLE
The custom keyboard shortcuts stop working after some hours

### ISSUE THREAD

**Issue by fxdave** [solus-project/budgie-desktop#1449]
*OS*: manjaro
*DE*: budgie-desktop v10.4-34-gd6f3519f

**The issue**
The custom keyboard shortcuts stop working after some hours.

**I have these keybindings:**
![image](https://user-images.githubusercontent.com/12275699/40365238-5dfb00ee-5dd4-11e8-9b13-53c396ae4898.png)

**Workaround**
Restart budgie-wm.

**Comment by fossfreedom** [comment]
This is tentatively a workaround that various people are currently testing

gnome settings -> region&language and there, click on “manage installed languages” then changed “keyboard input method system” to none instead of ibus. Logout and login

I guess there is some sort of race condition here with ibus and gnome-settings-daemon fighting  over keystrokes

**Comment by fxdave** [comment]
Thanks, 
But closing, because I switched to gnome. 
Later I may return back.
