### ISSUE TITLE
Solus dont want to open any system settings

### ISSUE THREAD

**Issue by GraxMonzo** [solus-project/budgie-desktop#1476]
Settings just dont show up.
I have gnome control-center but i get this error
```
zatos@dev ~ $ gnome-control-center
gnome-control-center: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
```

**Comment by Xmetalfanx** [comment]
I hate to speak for anyone on the Solus team but sometimes (regardless of the DE of Solus your on) I have seen stuff like that and the solution ... double check the software center and do all the updates .... instead of troubleshooting for longer than is needed, a time or two that I have seen that sort of thing (not saying its the same "error" btw) ... a simple "apply all of the newest updates" fixes this ... I CAN'T comment if you're on the Solus Unstable branch in case they are updating things there ..

IF YOU have no idea what "the solus unstable" branch is ... then your on the normal "stable" branch, btw

**Comment by GraxMonzo** [comment]
fixed it by updating gnome control center !
