### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Ringstaart** [solus-project/budgie-desktop#151]
I ran into problems when trying to compile Budgie on Debian. To successfully compile it, I had to install libtool. To then actually run it, I had to install gnome-settings-daemon.

Can these be added to the list of dependencies?

**Comment by ikeydoherty** [comment]
Hi. It's expected that your distribution provides a sane build environment to start with by means of a sensible component or metapackage, such as build-essential.

gnome-settings-daemon is indeed mentioned in the README, however it is *not* an explicit runtime dependency. The only reason it is needed is to dynamically update the XSettings to export the current theme information, etc.

I would argue that gnome-settings-daemon is a recommendation, not requirement (to use Debian packaging terminology)

**Comment by Ringstaart** [comment]
build-essential was installed on my system, but libtool was not. It appears that build-essential doesn't have libtool as a dependency on Debian. Even if this is a mistake on Debian's part, it might be a good idea to add it to the dependency list anyway. I was warned about it by the configuration script, however, so anyone who doesn't have it installed should figure out what they're missing easily.

budgie-wm refuses to run without gnome-settings-daemon installed. I verified that it's not one of its dependencies that I happened to need as well, by removing gnome-settings-daemon, but not its dependencies. This is the full error message it gives.

```
(budgie-wm:18847): GLib-GIO-ERROR **: Settings schema 'org.gnome.settings-daemon.peripherals.mouse' is not installed

Trace/breakpoint trap
```

I didn't install gnome-settings-daemon because of the README, but because of that message.

**Comment by Ringstaart** [comment]
I found that I also needed the gnome-menus package to get the menu working (it was empty, except for the search bar, before I installed the package).

There are still other functions that are not working properly, such as logging out using the panel putton, and setting a background (it's currently black). I suspect those are also caused by packages I haven't installed yet.

But I've seen enough of it that I'm going to use it when I get it to work right. I'm impressed so far.

**Comment by ikeydoherty** [comment]
That error has nothing to do with budgie-wm, that's mutter itself. Again this is a packaging issue in Debian. If mutter is accessing a schema (read: file) from another packages contents it is up to Debian to provide the correct runtime dependency. Given they have both a borked build-essential concept (if you autoreconf *anything* you need libtool) and mutter packages (what is up with those suffixes..) I will add gnome-settings-daemon to the README, likely with an accompanying rant.

You'll also notice that libgnome-menus is a build time requirement, and in most distributions this has been fine (Evolve OS included), but apparently Debian again has weirdness in this respect. Long story short if we build against something, we expect it to be there at runtime. 

An example from Evolve OS's packaging..

```
Package libgnome-menus has file /usr/share/desktop-directories/AudioVideo.directory
Package libgnome-menus has file /usr/share/desktop-directories/Utility-Accessibility.directory
Package libgnome-menus has file /usr/share/desktop-directories/System-Tools.directory
```

It looks like Debian splits it out and doesn't make it a dependency:
https://packages.debian.org/sid/amd64/gnome-menus/filelist

Thanks for bringing these to my attention. Not your fault the packaging is iffy. 
Re: wallpaper, the fallback for an invalid wallpaper is a black screen, this helps us to triage the issue. If you use gnome-control-center to alter your background (or anything else with knowledge of the org.gnome.desktop.background GSettings) to anything that *isn't* a .xml file (the GNOME default is Adwaita timed.) then it will update.

The .xml files are simply slideshows, that budgie-wm doesn't *currently* support, which is why this is such a common issue, given its the GNOME default. It is something that I intend to address, as it increases compatibility with GNOME. :)

**Comment by ikeydoherty** [comment]
Ok not autoreconf *anything*. But the vast majority. Anything using libtool. :P My issue with listing libtool is its a known thing you'd have. Then I would also be adding gcc, glibc, automake, autoheader, etc, for the build dependencies.. 

If there are other things missing let me know.. Looks like I have no choice but to account for it.

**Comment by Ringstaart** [comment]
Thank you for your help.

I didn't have gnome-control-center installed. I did try nitrogen and feh to set the background, but those didn't work. Using gnome-control-center, I could set the background.

A placeholder background color other than black would be better, I think. With plain black, many details become invisible - the workspace switcher was mostly invisible when I added it to the panel, the status area frame was invisible, etctera. Some shade of grey wouldn't harm functionality.

I didn't get the log out button to work yet (suspend does work, I haven't tested shut down and reboot). Is it possible that that is because of the way I'm running it? I'm running "startx /usr/local/bin/budgie-session" on a tty to start, and running "killall budgie-session" to exit. I don't have a display manager installed.

**Comment by ikeydoherty** [comment]
Logout is a long standing issue, its not specific to your setup. Fwiw /usr/local isn't recommended, especially on Debian with its multiarch getup. Kudos for getting this far :)

**Comment by Ringstaart** [comment]
I suppose installation to /usr/local worked because I used a 32-bit version of Debian, on a fairly old netbook. There was no multiarch support.

I also installed it on my desktop pc, which is running 64-bit Debian. I used the same setup, but with /usr instead of /usr/local/. Logging out does work here. Other than the missing background before changing it, it seems to be working flawlessly now. Again, thank you.

**Comment by Justinzobel** [comment]
https://evolve-os.com/wiki/Budgie/Install Debian build instructions.

**Comment by ikeydoherty** [comment]
Closing as I see no issue here anymore.. Debian is a constant source of pain we cannot control.

**Comment by DJviolin** [comment]
Wiki page removed from the site.

**Comment by ikeydoherty** [comment]
@DJviolin and missing site too, perhaps? evolve-os.com is gone. The build dependencies are listed in this repository, where they should be.
