### ISSUE TITLE
Expain Budgie positioning, please. 

### ISSUE THREAD

**Issue by rilian-la-te** [solus-project/budgie-desktop#1550]
**Operating System**: not relevant
**Budgie version**: latest master

**The issue encountered**

 I want to know how a panel position applets inside its layout. AFAIK I know from its source, it attach 3 boxes, set one on left, one on right, and one via gtk_box_set_center_widget. 
If we talk about https://gitlab.com/vala-panel-project/vala-panel-appmenu/issues/222, then I can explain, why I decide than it is a Budgie bug. 

1. Center box is always visible and always on center (even if no center applets encountered). 
2. It has higher priority than other boxes, if measured by natural width (except if pushed by minimal width) 
3. My applet set natural width as high as menu size, but minimal width is a size of one menu item (menu itself is scrollable, so, one menu item is enough) 
4. So, because this is a technically visible empty center box, menu get truncated. 
5. In old version, menu was not scrollable, so, it pushes out center box. 

I think, this bug can be resolved by hiding center box, if no center applets exists, and show it only with applets. 
**Steps to reproduce the issue**
This is an question.

**Comment by rilian-la-te** [comment]
@fossfreedom what do you think about it?

**Comment by fossfreedom** [comment]
My view is just a view and I obviously don't  represent upstream in anyway.

It does seem reasonable to me that the panel boxes should hide themselves if no applets exist in them.  

I assume some inspiring dev could propose a patch but as I said I have no idea if such a patch would be accepted.

**Comment by rilian-la-te** [comment]
> It does seem reasonable to me that the panel boxes should hide themselves if no applets exist in them.

So, you think than pushing away center applets (or even push out last applets) is better solution (it will happens with long menus, if I set minimal width as equal as full menu)?
So, I think, they do) (and in my own panel, will)

**Comment by JoshStrobl** [comment]
Closing this task, I will not be addressing issues / providing support that just end up in `vala-panel` when you strip away our GPL headers from our code, such as [this file](https://gitlab.com/vala-panel-project/vala-panel/blob/master/applets/wnck/icontasks/appsystem.vala).

**Comment by rilian-la-te** [comment]
@JoshStrobl as you requested:
1. Headers readded [this file again](https://gitlab.com/vala-panel-project/vala-panel-applets-gpl/blob/master/icontasks/appsystem.vala)
2. Repositories split (to save your GPL) [new repo](https://gitlab.com/vala-panel-project/vala-panel-applets-gpl)

If I have more headers than should be attributed and GPL'ed, please, write me. I do not want such clashes.

**Comment by JoshStrobl** [comment]
> because I borrowed some GPL code and developers refuse to provide this code as LGPL

I don't really approve of this sort of behavior. Not sure why you're being so aggressive about this rather than respecting that someone put time into writing this code and simply want the license to be respected? I'm going to mark this conversation as locked, I wish you the best of luck in the future with your project and hope that you decide to either re-implement this code or continue to respect the licenses of various parts of Budgie. Given the actions (consciously deciding to remove license headers) and attitude presented by yourself I can't in good conscious continue to assist you. I'd rather focus my attention (and limited time as a volunteer, having a job which isn't Solus) on Budgie users and downstreams like Ubuntu Budgie.
