### ISSUE TITLE
Bug in projecting screen and themes "Adapta" and "Adapta-Eta"

### ISSUE THREAD

**Issue by valle50** [solus-project/budgie-desktop#1639]
**Operating System**: Solus 3.9999
**Budgie version**: v10.4-85-g36667bcb

**The issue encountered**

    1- It does not detect the secondary screen to extend the desktop when connected by VGA. It only 
     detects it until you enter the "screen" settings.
    2- The "Toolbar" of some applications does not show the tabs.

**Steps to reproduce the issue**
    1- When I turn on the PC, I connect the screen with VGA and when Solus starts, It do not detect the 
     screen even if I press the combination "fn + f7" to project. It only detects it when you enter the 
    "screen" configuration.
    2- When choosing the theme "Adapta" or "Adapta-Eta". It only happens with those 2 "themes".

"Adapta" and "Adapta-Eta" themes
![captura de pantalla de 2018-12-05 22-31-54](https://user-images.githubusercontent.com/30840342/49561597-b8ff4c80-f8dd-11e8-8153-e3733489a2fe.png)

Others who do not have that problem.
![captura de pantalla de 2018-12-05 22-31-25](https://user-images.githubusercontent.com/30840342/49561609-c1578780-f8dd-11e8-90c6-4759bcfd6f02.png)

**Comment by ThePiGuy0** [comment]
Maybe this issue is old and no longer needed, but I thought that I would add that the 2nd issue (toolbar not showing) is not an issue related to solus or budgie. It's an issue in electron 2 apps (this is the issue page for atom for example - https://github.com/atom/atom/issues/18535)

A workaround is to launch the app with dark gtk theme parameters
