### ISSUE TITLE
Two Network entries in the Super menu

### ISSUE THREAD

**Issue by dandv** [solus-project/budgie-desktop#1650]
Fresh live boot of the ISO downloaded today, so Budgie 10.4.

Press Super, type "netw".

![double network](https://user-images.githubusercontent.com/33569/49692076-d7e02780-fb05-11e8-9bb1-4163293285b1.png)

**Comment by yursan9** [comment]
I can't reproduce the bug on Solus Budgie. Can you check the menu entries using something like MenuLibre? Maybe there is duplicate menu entry for Network.

**Comment by yursan9** [comment]
Well, you make it kinda hard to analysis the issue. Like I said, I can't reproduce the issues on fully updated Budgie on Solus. It's likely the issue was already solved if you install Ubuntu Budgie and update the budgie-desktop. @fossfreedom Can you help shed some light to this issue?

**Comment by JoshStrobl** [comment]
Unable to reproduce on Budgie under Solus, which leads me to believe that there are multiple **valid** categories set for the Network desktop file, which is why it's showing up under All multiple times, just like any application with multiple categories would.

The one for Solus: `Categories=GNOME;GTK;Settings;HardwareSettings;X-GNOME-Settings-Panel;`

Effectively, working as intended.
