### ISSUE TITLE
Per App volume control has speed-dispatcher

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1688]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

Idk how it appears, when I use firefox, when I went to volume control after watching some videos
specially after watching in FB, I noticed this 4 speech-dispatcher volume controls which disappears if closed firefox. & I tried to figure it out how it appears at the first place (the cause), but I failed. As I noticed it seems it only comes after using FB.

![screenshot from 2018-12-30 13 07 00](https://user-images.githubusercontent.com/38057676/50548264-a4f60300-0c6f-11e9-828e-b403fcc0cf18.png)
 

**Steps to reproduce the issue**

Open firefox(Idk weather it happens with other browsers), watch videos in any site, plus in FB
open raven & see what's there

**Comment by JoshStrobl** [comment]
We don't control what Gvc Streams Firefox creates, not really anything I can do here besides having it outright ignore those items and not show them, but that'd mean you would lose control of those.

**Comment by JoshStrobl** [comment]
Seems to be an issue with speech synthesis apis and Firefox. It was [reported over 3 years ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1252732) and indicated as resolved, clearly wasn't the case. Since there isn't any plans on outright disabling `media.webspeech.synth.enabled` in at least the Solus default configuration, since that would negatively impact various integrated screen reading functionality in Firefox and thus accessibility, not to mention it's not a Budgie issue but rather an issue with Firefox, I'm going to consider this as a wontfix. If you wish to disable it yourself, you're welcome to go to `about:config` and set `media.webspeech.synth.enabled` to `false`.
