### ISSUE TITLE
Wrong URL in the repo description 

### ISSUE THREAD

**Issue by stchris** [solus-project/budgie-desktop#1849]
## Description

This repos description is 

```
I Tawt I Taw A Purdy Desktop https://solus-project.com/
```

but that URL leads to a 404.

## Expected result
Probably link to https://getsol.us/

**Comment by JoshStrobl** [comment]
I don't have the permissions to modify that (it involves GitHub repo settings) and the previous developer + project lead hasn't been able or willing to help me or anybody else on the Solus team to resolve various issues with access / permissions for the solus-project organization. Budgie 10 series developer will continue on this repo, since I at least have access to push commits and make releases, but Budgie 11 developer in the future will happen on the GetSolus organization.

inb4 asked about just redirecting: I intentionally do not have solus-project.com redirecting to getsol.us as that did not make it obvious to our users when the domain changed, for those that somehow didn't get the memo after months post-migration.

**Comment by apiraino** [comment]
I've landed to this project page and had to go back to a search engine to finally get to https://getsol.us

Maybe a pinned issue to have the new link more prominent?

Could (or was already) github be contacted to help with this issue?

just my .2 cents
