### ISSUE TITLE
"Oh no! Something has gone wrong." with latest update

### ISSUE THREAD

**Issue by nickcorona** [solus-project/budgie-desktop#1874]
## Description

Desktop environment doesn't start. Encounter white screen error mentioned below.

## Budgie version

budgie-desktop 10.5 (git-38b69f05619f0b1a681276dc258929f2fcb7a750)

## Operating system

Arch linux

## Steps to reproduce the issue

exec budgie-desktop

## Actual result

Oh no! Something has gone wrong.

## Expected result
login screen

## Additional information
This occurred with latest update.

**Comment by JoshStrobl** [comment]
Yea no, this is an issue with Arch, they're not using Budgie git and Arch users are reporting it under GNOME as well: https://bugs.archlinux.org/task/63849?project=5&string=budgie-desktop

**Comment by aedalzotto** [comment]
The same is happening with budgie-desktop-git

**Comment by JoshStrobl** [comment]
This is **not** an issue with Budgie. I am actively using Budgie across multiple devices on Solus, using the GNOME 3.34 stack. Make sure you are using the latest release of Mutter, gnome-session, etc. You'll also want to make sure you've recompiled your glib-schemas since GNOME moved some schemas to Mutter. This "oh no" dialog occurs if you haven't recompiled your schemas, I validated it personally.

Please consult the issue I referenced above for support for your distribution.

**Comment by smokku** [comment]
The problem is well described in Debian bugtracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942077
There also is a working fix there.
