### ISSUE TITLE
No tray icons with apps based on electron

### ISSUE THREAD

**Issue by KardinalReusen** [solus-project/budgie-desktop#1975]
## Description
I have several apps based on electron like e.g. keeweb or riot-desktop. The apps operate normal, but the tray icons are not displayed. I also used different electon versions (4-8).

## Budgie version
10.5.1

## Operating system
arch linux

## Steps to reproduce the issue
I have three arch linux PCs / notebooks with similar configuration. The tray icon problem shows up on every installation.

## Actual result
No tray icons

## Expected result
tray icons

**Comment by alecbcs** [comment]
Hey @KardinalReusen, your bug may be different since you mention trying different electron versions, but it sounds a lot like [this upstream issue](https://github.com/electron/electron/pull/23674) where the chromium team recently removed support for GTK tray icons. Recent versions of Electron have thus also dropped support for GTK tray icons even though many of us are using them.

**Comment by JoshStrobl** [comment]
Closing as this is an upstream issue that while affects Budgie, is not Budgie-specific. Thanks @alecbcs for the additional information on the matter.
