### ISSUE TITLE
Fully Automate Budgie Applet Installs?

### ISSUE THREAD

**Issue by rbreaves** [solus-project/budgie-desktop#2014]
### Current Budgie version
10.5.x

### Use-cases
I want to fully automate the install of a Budgie Applet

### Proposal
Provide a mechanism to properly install an Applet via the terminal. I do understand that currently a logoff and back on is required.

I assume any mechanism to do this would also need to figure out how to configure the entries in this dconf location /com/solus-project/budgie-panel/applets

**Comment by JoshStrobl** [comment]
> Provide a mechanism to properly install an Applet via the terminal. I do understand that currently a logoff and back on is required.

It isn't required. You can restart the panel. Logout / login just happens to be one of the more convenient means to do this, as applet discovery is done during panel initialization as we do a module probe and applet loading there. Otherwise we would likely need to perform other means of dynamically updating the applets loaded, adding / removing them as necessary, which would probably be a file monitor.
