### ISSUE TITLE
Implement the "org.gnome.Shell.Screenshot" dbus interface

### ISSUE THREAD

**Issue by lpinner** [solus-project/budgie-desktop#2027]
### Current Budgie version
budgie-desktop v10.5.1

### Use-cases
Enable applications relying on "org.gnome.Shell.Screenshot" dbus interface to work.  For example the colour picker tool GColor3 v.2.4.0 does not work under budgie [#120](https://gitlab.gnome.org/World/gcolor3/-/issues/120).  This particular tool is rather important for me as a person with colour vision deficiency (aka "colour blindness").

### Proposal
Implement the "org.gnome.Shell.Screenshot" dbus interface

### References
#261 references commits 39f2ec7 &  e10d621 "Implment screenshot functionality leveraging GNOME Screenshot."  ticks the "Lacks support for taking screenshots with Print screen keybinding" item, but does so by shelling out to the `gnome-screenshot` commandline tool rather than implementing the "org.gnome.Shell.Screenshot" dbus interface.

**Comment by JoshStrobl** [comment]
We're not based on GNOME Shell, we can't possibly assume that the interface would be there, and it wouldn't be functional seeing as we're only so much a "GNOME" session as we report as `Budgie:GNOME` to Mutter.

Applications just need to stop assuming they're running under Shell.

**Comment by BrainBlasted** [comment]
Instead of implementing the dbus interface, this could also be resolved through Budgie having an xdg-desktop-portal implementation. There's nothing I can do on the Color Picker app side, but if Budgie had an implementation of the portal, that could be used instead of xdg-desktop-portal-gtk (which relies on GNOME Shell for the color picker/screenshot portal)
