### ISSUE TITLE
Budgie Panel unresponsive when upowerd has problems - status indicator flaw

### ISSUE THREAD

**Issue by JacekJagosz** [solus-project/budgie-desktop#2031]
## Description
When upowerd starts using 100% of one thread the budgie panel becomes unresponsive, and a click causes an action a minute or 2 later. 

## Budgie version
Budgie 10.5.1

## Operating system
Solus 4.1

## Steps to reproduce the issue
This is an edge case. My 2in1 with 2 batteries first completely depletes battery in the keyoard, and then in the tablet. When battery in the keyboard is almost depleted, upowerd starts using 100% of one thread, budgie panel becomes unresponsive. They come back to normal when that battery gets completely depleted and it starts using the other one. **That happens only if I have status indicator equipped, without it there is no problem.**

## Actual result
When the panel becomes unresponsive it is very hard to use the device and figure out what is going on, unless you know keyboard shortcuts.

## Expected result
I'm not expecting for this issue to be fixed, as it is a problem specifically with my hardware, I'm just pointing out that status indicator has that specific bug, and one applet can render entire panel unresponsive. I don't know if that could be done better with Budgie 11, but it looks like a design flaw.
Feel free to close this, this is no big deal.

**Comment by JoshStrobl** [comment]
While I certainly understand the frustration, this has been a multi-year issue with upowerd specifically and unfortunately isn't specific to Budgie, for example it's happening [with Pantheon as well](https://gitlab.freedesktop.org/upower/upower/-/issues/15), [likely GNOME Shell as well](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1494). It even happens when other devices like an [iPhone](https://gitlab.freedesktop.org/upower/upower/-/issues/79) are connected. It's likely an issue with how upowerd is trying to fetch the battery information.
