### ISSUE TITLE
gnome-shell and budgie-screensaver now conflicts

### ISSUE THREAD

**Issue by SolarAquarion** [solus-project/budgie-desktop#2120]
I think the idea is to now change budgie-screensaver to move from gnome-screensaver, and simply apply the screensaver as budgie-screensaver, including related changes in the program.  It would be a similar program to cinnamon-screensaver

**Comment by JoshStrobl** [comment]
I have no idea what you mean by this. budgie-screensaver is a fork of gnome-screensaver, the lock screen for GNOME Shell is provided by GNOME Shell itself, the login greeter is separate (Solus ships with lightdm+slick-greeter for our flagship image, GDM -- which is required for the GNOME Shell experience -- is part of the Solus GNOME Edition).

**Comment by SolarAquarion** [comment]
gnome-shell 4.0 now provides org.gnome.ScreenSaver.service, which conflicts
with the budgie-screensaver, since that also provided
org.gnome.ScreenSaver.service

**Comment by JoshStrobl** [comment]
Should be filed at https://github.com/getsolus/budgie-screensaver as well

**Comment by SolarAquarion** [comment]
I can't file anything on budgie-screensaver

**Comment by JoshStrobl** [comment]
Sorry try again

**Comment by fossfreedom** [comment]
I have raised this on GNOME Shells issue tracker https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4100

**Comment by fossfreedom** [comment]
@JoshStrobl given the reply by the GNOME Dev, I'm guessing that Solus's Budgie Screensaver will effectively be the mandatory component for Budgie Desktop moving forward? That will also include managing all potential security issues inherited from gnome-screensaver (since budgie-screensaver is a fork of).   The only other actively maintained X-based screensaver is the grand-daddy  xscreensaver ... don't know if you want to consider that route until Budgie 11 can properly re-architect things?

Upstream mentioned gnome-settings-daemon in its reply - so does this mean Budgie now has to fork gnome-settings-daemon?

Sounds like Debian and Ubuntu / all distros should in future remove GNOME Screensaver from their repos.

**Comment by JoshStrobl** [comment]
Not really sure why you raised this with them. It's our fork, they haven't been developing it for almost a decade. The reason why it is a fork is because our previous attempts at becoming the maintainers failed, so we opted to fork it. Budgie 11 will have a different path going forward.

1. Yes, budgie-screensaver has always been a mandatory component. We have always indicated that people should be using our budgie-screensaver fork.
2. The "security" issues are frankly blown out of proportion, but we've never been hesitant to work with other developers in improving this screensaver.
3. We don't need to fork gnome-settings-daemon, the code referenced is in gnome-shell and it's the dbus interface that GNOME Shell calls.

**Comment by fossfreedom** [comment]
> budgie-screensaver has always been a mandatory component

Really?!  Must have missed that for many years.  Debian/Ubuntu uses gnome-screensaver. Canonical have been maintaining that with various patches  (support ends very soon).  So may be something there to grab if you wish.

**Comment by JoshStrobl** [comment]
> > budgie-screensaver has always been a mandatory component
> 
> Really?! Must have missed that for many years. Debian/Ubuntu uses gnome-screensaver. Canonical have been maintaining that with various patches (support ends very soon). So may be something there to grab if you wish.

Yep but I'm happy to pull in any patches if you have recommendations. For that, please reference the correct repo linked earlier in the discussion. Thanks!
