### ISSUE TITLE
Dark Theme won't activate

### ISSUE THREAD

**Issue by DaveR27** [solus-project/budgie-desktop#2129]
## Description

The dark theme will not activate completely with the UI button in budgie settings

## Budgie version

Basic data partition

## Operating system

OS: Arch Linux x86_64 
Kernel: 5.11.15-arch1-2 

## Steps to reproduce the issue

I just flicked the button and it didn't work

## Actual result

![budgiedarkissue](https://user-images.githubusercontent.com/30149018/115200537-ad6ff180-a137-11eb-874c-08869f2b0112.png)

## Expected result
Should be dark theme

**Comment by JoshStrobl** [comment]
1. Using Adwaita isn't supported, which is what "Default" is. You should be using something like Plata.
2. In order to fully handle weird cases where a theme doesn't fully implement dark theme support and we need both the theme selected and dark theme toggled on, we need to implement theme changing to handle variant changing. This is already planned.
