### ISSUE TITLE
Calendar day highlighted isn't updated when day changes

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/budgie-desktop#215]
If device left on overnight, calendar still highlights the day the device was booted, it doesn't update. This also affects budgie-next.

**Comment by tista500** [comment]
Really?

Mine (8.2-git on Ubuntu) seems to work normally though...

**Comment by Justinzobel** [comment]
Doesn't work on Solus.

**Comment by tista500** [comment]
@Justinzobel I'm sorry I was wrong. Today I could confirm this issue, I can't notice this because sometimes badgie-panel reloads itself by errors often...

Regards.

**Comment by Justinzobel** [comment]
@ikeydoherty this code work? ^

**Comment by ikeydoherty** [comment]
This was fixed a long time ago and then removed..

**Comment by JoshStrobl** [comment]
I'd appreciate if this this bug was reopened (regarding Calendar applet in Raven):

1. It doesn't change.
2. Ideally the days shouldn't even be clickable in the first place. Clicking the days doesn't  do anything aside from highlight the day (which then doesn't get updated to the actual date, including during day changing).

**Comment by JoshStrobl** [comment]
@ikeydoherty Fixed as of 762b9856a71c8229324a4fec1a1992c4f12b7ae6

Please close :smile:
