### ISSUE TITLE
Request to add new language

### ISSUE THREAD

**Issue by itsnotsaved** [solus-project/budgie-desktop#2152]
#### Proposal
- [ ] Request to add sinhala language for [budgie-desktop](https://translate.getsol.us/projects/budgie-desktop/translations/)
  (somehow, it's already available for [brisk-menu](https://translate.getsol.us/projects/brisk-menu/) without translations)
- [ ] Set necessary permission to weblate user `helabasa` for save translations directly.
(I also contribute to many projects on https://hosted.weblate.org then it's not necessary to doubt)

### References
Please note, i only found this page https://getsol.us/articles/contributing/getting-involved/en/#translations related translation however i'm sorry if this isn't right place to inform about that)

**Comment by JoshStrobl** [comment]
The correct process is to provide details via [our forum](https://discuss.getsol.us/d/5774-call-to-action-translators-needed) on what certain languages are not seeing reviews. If there is no translator team for it, I may end up creating one and assigning you to it. Otherwise, you will need to exercise patience.

**Comment by itsnotsaved** [comment]
@JoshStrobl see https://discuss.getsol.us/d/5774-call-to-action-translators-needed/95
