### ISSUE TITLE
Fraud?

### ISSUE THREAD

**Issue by diegogarciaa** [solus-project/budgie-desktop#247]
Ok, So I was in the solus website, there was a fund raiser propaganda, and at some point, the author said he was going to launch solus os in october first day...

So, where da fuq are you? You asked for money (which I gave), and you just disappear? Why you do this? This is not the first time this happens...

**Comment by feskyde** [comment]
Budgie desktop development is frozen because @ikeydoherty is making a rewrite in C, see [here](https://github.com/ikeydoherty/budgie-panel).

**Comment by diegogarciaa** [comment]
Maybe those glasses aren't working... Everything I wrote was about Solus OS.

It seems Buggy Desktop is not the only thing "frozen"

I am pissed off because the ikeydoherty, despite being called out a dozen of times, does not even care...

**Comment by Justinzobel** [comment]
This type of attitude doesn't do you any favours. A simple what is
happening with Solus might work better in future.

So, if you had followed any number of our social media outlets you might
know that we had some unfortunate delays in that our build infrastructure
died, Ikey's internet also died and then he had work commitments to attend
to. He can only work on Solus in his spare time, the same as the rest of
us, he has to eat, sleep (contrary to popular belief) and work so he has
money to continue working on Solus.

Due to this streak of bad luck we decided not to put a date on Solus 1.0's
release, it will be here soon though.

If you'd also cared to take a look around the forums, IRC, Google+ not to
mention our build/git pages you'd have seen that work is still going on
with Solus, Budgie etc. So NO, this is NOT fraud. The donations were not
our users paying for a service or product, they are donations in order to
assist Ikey getting certain hardware enabled and infrastructure necessary
for Solus to continue on.

**Comment by diegogarciaa** [comment]
Shut the fuck up... You guys are a fucking mess... Look at this github repository, is a fucking disaster. The website THERE IS NOTHING talking about THE FUCKING IDIOT THAT IS GOING TO LAUNCH A OPERATIONAL SYSTEM AND STAYS WITHOUT INTERNET...AND DID EVEN FUCKEN CARE ENOUGH TO WRITE A 5 LINES BLOG ON HIS FUCKING WEBSITE???

HOW SHIEEETTT YOU GUYS ARE???

**Comment by Justinzobel** [comment]
Reported. No point in trying to convince you.

**Comment by ikeydoherty** [comment]
Called out? Fraud? Dude go check our G+ page, hell even Softpedia have covered our delays. Work is *actively* ongoing. Go check https://build.solus-project.com/
Or even https://git.solus-project.com/

Lastly, wind your fucking neck in and learn some respect for people. It's precisely people like *you* that make people *not* want to work on projects. This project is completely transparent, and we *constantly* keep people updated. If you're somehow not aware of where we're currently at as a project, then the problem lies *with you*.
