### ISSUE TITLE
Budgie isn't obeying configured GTK3 theme (possible GTK 3.16 bug?)

### ISSUE THREAD

**Issue by geckolinux** [solus-project/budgie-desktop#304]
Hi there,

I distribute an openSUSE Leap 42.1 spin with Budgie. I've been seeing a theming bug which might be related to the older GTK 3.16. Here's what I see by default with Budgie 10.2.2:

![screenshot from 2016-01-03 06-13-28](https://cloud.githubusercontent.com/assets/2692138/12079362/dec4ea7a-b203-11e5-9803-a01464c7f064.png)

After toggling the "built in theme" switch on and off again, it looks like this:
![screenshot from 2016-01-03 06-13-52](https://cloud.githubusercontent.com/assets/2692138/12079363/fbc697d6-b203-11e5-98c1-0ca8c44d11b0.png)

But I would like it to use the Numix style throughout the interface, including a dark panel with red accents.

Thanks for looking into this!

**Comment by ikeydoherty** [comment]
Budgie doesn't obey the configured GTK theme  because no GTK theme supports Budgie.

Therefore to provide a consistent UX we override the majority of the theme.
We expose the "built-in theme" option precisely so that in future, GTK themes can override what we specify.

I imagine even a simply amount of patching to Numix can achieve what you're looking for. Simply copy the PanelToplevel styling across for .budgie-panel and go from there :)

**Comment by geckolinux** [comment]
Ok thanks Ikey for the pointer!
