### ISSUE TITLE
Avoid extinction through GNOME Dependency

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/budgie-desktop#313]
Currently Budgie focuses on tight GNOME integration, but approaches it in such a fashion that will undoubtedly lead to the extinction of the project. Whilst integrating into the GNOME Stack is assuredly good, relying on the GNOME stack *components* is just silly.

Reasoning: Many of the components we use and need for desktop functionality are also components needed for GNOME Shell functionality.

TL;DR: These components are specifically for GNOME now. We need more cross-desktop building blocks.

Extremely High Risk Components:
-----------------------------------------------

The use of the following components require extreme hacks, workarounds or ugliness to accomplish. They should be extensible to the desktop in question, and modular where appropriate. We should not just *assume* they will be using, for example, `org.gnome.*` GSettings keys. Eventually a full Budgie session would be able to run side by side with a GNOME Session, and not conflict or alter one another's settings.

**GNOME Settings Daemon** - far too tightly integrated into GNOME's system and *explicitly* requires the org.gnome.Shell interfaces. Without the severe butchery we see in `budgie-wm`, integration is a no-go. Replace this with a cross-desktop `libsettings-daemon` in C.

**GNOME Control Center** - Again, tightly integrated for the GNOME Shell Experience. Once upon a time this was modular and open to extension, however it reflects the state of the rest of the stack in being completely targeted to the use of GNOME Shell Desktop Experience only. Again, replace the commonality, perhaps liaise here with elementaryOS to provide a core library to be configured to the use of each desktop. They've done excellent work with Switchboard. Perhaps a `libsettings-center`

**GNOME Session** - Somewhat obvious, really. A simpler and more extendible API could be provided here to enable use on multiple platforms and desktops, and again, dropping the extreme dependency on `org.gnome.Shell` interfaces. Advise, `libdesktopsession`, and allow for both Wayland and X11 functionality.

**GDM** - Alright, so it's _just_ a login manager. However the reality is that in order to _use_ GDM, you must also have GNOME Shell. For a downstream desktop this is indeed unacceptable, not to mention that GDM is *running* GNOME Shell on the login screen. In Solus alone this adds an enormous amount of overhead to a single user system. Drop it, and use LightDM. For 2.0 we'll need Wayland support, so we'll start working with the LightDM people towards Wayland goals (let's see if they're responsive to this goal)

Medium, deprecation risks:
-------------------------------------

**gnome-menus** - Ancient by anyone's reckoning. Simply using GDesktopAppInfo is sufficient in replacing this. Do the categories work ourselves, if required we can make a submodule to account for this and translations. 

**Vala** - All evidence suggests that no work is happening on the compiler front in Vala, and GNOME is showing a tendency today towards the use of JavaScript and Python for primary app development. While there is no *immediate* evidence Vala is about to kick the bucket, let's not be stupid and just deprecate it's use in the *core implementation* of Budgie (We can still enable this for extensions, s'all good.).

While the rationale for Vala deprecation may seem strong, let us not forget that 2 years ago we figured integrating all of this into the GNOME stack in this way was a Good Thing™. Life won't let you down if you're expecting a reminder on how stupid you can be.

Long Term Thoughts
-----------------------------

**libmutter** - This isn't actually *as bad* as the other components, and Jasper has proven to be very helpful. However, with the 2.0 goals of Wayland only for Solus, we may indeed look further afield to find implementations better suited to an agnostic approach than libmutter, or indeed roll our own if needed (probably not)

Implementation Status
--------------------------------

- [ ] Replace GNOME Settings Daemon
- [ ] Replace GNOME Control Center
- [ ] Replace GNOME Session (Again)
- [ ] Replace GDM
- [ ] Drop use of libgnome-menus
- [ ] Remove Vala from the *core implementation*
- [ ] Breathe easily once more.
- [ ] libmutter re-evaluation (Long term)

**Comment by ikeydoherty** [comment]
Don't care anymore. We'll work out issues as we go along.

**Comment by nazar-pc** [comment]
I just want to add that I really appreciate that you're at least thinking about this!

My use case is not Solus OS and not even Budgie Desktop in general. I'm crafting own small custom session for own use (Compiz+Unity Settings Daemon+Plank+Budgie panel right now) based on Ubuntu. It is extremely painful for me (as I'm web developer, not working on DEs) to bring together what I want because of GNOME3 components being incredibly tightly coupled into pieces that shouldn't be together (like Mutter handling hotkeys). It is impossible to use G-S-D hardly depends on Mutter, while I want Compiz (thankfully, U-S-D despite own weaknesses works autonomously). Wingpanel from Pantheon (Elementary OS) depends on Gala (Mutter fork). Budgie panel depends on budgie-wn (Mutter fork I believe?) albeit it partially works and is still useful. Literally, the only 2 components I have literally no problems are: Compiz and Plank.

If you make your components relatively independent (Elementary OS work towards this already), I'd be happy user of your components and will support project in different ways to ensure it matures and enriches far into the future.
