### ISSUE TITLE
[Applet request]Removable media

### ISSUE THREAD

**Issue by Redneckita** [solus-project/budgie-desktop#429]
Hello everyone, i'm currently really happy with budgie desktop altough i miss some little feature (like window spread but it's already asked here) anyway, back to the point: i would like to have on the panel (near the systray) or on raven an applet that lists removable media and a button to remove them, instead of opening the file manager to unmount drives, what do you guys think?
Cheers and keep up the good work!

**Comment by diazbastian** [comment]
I think the bug #433 is a duplicate.
I like the idea that it is an applet that appears when a new device is connected.  As a further suggestion, in addition to the "Remove Drive Safely" add option "turn off this device" that is required in some external HDD (usually I use gnome-disks for this).

**Comment by ikeydoherty** [comment]
Implemented by @cybre in the new Places Indicator

**Comment by diazbastian** [comment]
@cybre I was testing the new places indicator and I have only activated "removable show media" and "Show network folders". However, when you insert a flash drive or external HDD is not automatically shown on the indicator, unless you open the folder manually. Is this an expected behavior?.

![media](https://cloud.githubusercontent.com/assets/5126124/19027557/16b4424c-8908-11e6-819b-78e3d934bccc.jpg)

Compared to network folders, they are automatically displayed in the places indicator.

![media2](https://cloud.githubusercontent.com/assets/5126124/19027559/23432366-8908-11e6-9432-a8c8fc2e660e.png)

**Comment by cybre** [comment]
The drive must be mounted for it to be shown in the indicator.

**Comment by diazbastian** [comment]
> The drive must be mounted for it to be shown in the indicator.

I see, I thought the indicator would behave like Nautilus or another file manager and can directly mount the device from the applet.

Thank you very much.

**Comment by cybre** [comment]
@diazbastian I have decided to change this behaviour. The indicator will show all interesting volumes even if they're not mounted.
