### ISSUE TITLE
New badge for Unity Greeter

### ISSUE THREAD

**Issue by IlyaBizyaev** [solus-project/budgie-desktop#434]
Hi!
I've designed a badge for unity-greeter. It should be installed to "/usr/share/unity-greeter", named "custom_budgie-desktop_badge.png".
Here is the result:
![img_20160503_123813](https://cloud.githubusercontent.com/assets/11175213/14979910/00b0470e-112e-11e6-88c4-65dd28ea48d8.jpg)
And here is the file itself:
[budgie-badge.tar.gz](https://github.com/solus-project/budgie-desktop/files/246638/budgie-badge.tar.gz)
That's more a pull request than an issue - but I just don't know where to put it :)

**Comment by fossfreedom** [comment]
can I suggest not really a Solus issue - more of a ubuntu issue I would suggest.

However - FYI we've got a request for this via the appropriate project to add a greeter for Unity which has been accepted and will appear in the ubuntu repo's at an appropriate point

 - https://bugs.launchpad.net/ubuntu/+source/unity-greeter-badges/+bug/1562182

**Comment by IlyaBizyaev** [comment]
My version looks better :laughing:

**Comment by ikeydoherty** [comment]
@fossfreedom are you forgetting that Budgie is cross-distro?

**Comment by ikeydoherty** [comment]
i.e. lets not start having a disparate ecosystem of support in hard to find places in Ubuntu, it's one of the things I hate most about it.

**Comment by fossfreedom** [comment]
Hmm? I'm aware that greeters tend to be distribution specific but if the unity greeter is something you are looking at then feel free to pull this into the project.  Under Ubuntu all unity greeter icons have now been consolidated under one project ... You could pull all the unity greeter icons for all desktops as well into a solus package which would include the budgie desktop icon which that particular project has accepted.

If you do pull this into budgie desktop then that is your prerogative.  I will just have to patch it out under Ubuntu because the same file is delivered by the other project.

**Comment by ikeydoherty** [comment]
@fossfreedom I'm more concerned about people who are less in the loop than we are, tbh :) Note how this bug came about because the OP didn't know you'd pushed to unity badges, just proving my point.

It's up to you guys how things are handled over in Ubuntu land, just tryna offer some advice on how to avoid future pitfalls that will come back here.

**Comment by fossfreedom** [comment]
k - understand.  Equally trying to help the OP.

**Comment by ikeydoherty** [comment]
@fossfreedom clarify for me please: Did you have the *Budgie Remix* icon set as the *Budgie Desktop* icon in unity-greeters? Your bug seems to indicate that.

**Comment by fossfreedom** [comment]
no - we stepped back (later in the bug-report) - the icon is the standard budgie-desktop icon from Yuri.  As I understand it, @hexcube approached Yuri to gain permission to add the icon.  i.e. budgie-desktop == solus project as it should  be just like "gnome 'foot'" is gnome etc

**Comment by ikeydoherty** [comment]
@fossfreedom I'll talk with you by G+.

**Comment by HEXcube** [comment]
Looks like this turned out to be pretty confusing! :sweat_smile:

Well, like @fossfreedom already mentioned, we submitted the Budgie logo for budgie-desktop session for inclusion in upstream [unity-greeter-badges](https://bugs.launchpad.net/ubuntu/+source/unity-greeter-badges/+bug/1562182) project. The change'll reach the Ubuntu repos by next cycle 16.10. :smile: But for 16.04 we already made the updated packages available in Development PPA. It'll reach the stable PPAs after a bit more testing.

The logo we submitted was derived from [the monochrome symbolic version by Yuri Henrique](https://www.dropbox.com/sh/tbk1qozkzdh2642/AABRxPRGxwNnwQNPdgZx1F1Aa/Budgie-Menu-Icon/view-grid-symbolic.svg.mono). U can view it on [our GitHub repo](https://github.com/budgie-remix/assets/blob/master/Logos/Budgie/budgie-symbolic.svg).

The reason we used _Budgie_ logo instead of _budgie-remix_ logo, is that we're still shipping vanilla budgie-desktop session without any rebrand. Once we complete the rebrand by next cycle, then we'll use budgie-remix (or ubuntubudgie if we become an official flavor). Hope this cleared all the confusion. :relaxed:

**Comment by ikeydoherty** [comment]
@HEXcube no I'm the confused one. So ya as I said to @fossfreedom my concern is keeping the main vanilla Budgie Desktop, well, vanilla. Even Solus must abide by those rules and ensure customisations specific to our way of things is done *properly* - i.e. the budgie-desktop-branding package here on GH.

**Comment by ikeydoherty** [comment]
Sorta at the point now Budgie needs a `--with-vendor` string lol..

**Comment by HEXcube** [comment]
Well, I didn't try submitting the logo to Solus coz Unity Greeter is mostly a Unity thing u know. :sweat_smile: Didn't think it was relevant for the Solus package.

But we submitted a similar logo for upstream LightDM GTK Greeter too: [a budgie symbolic svg logo](https://bugs.launchpad.net/ubuntu/+source/lightdm-gtk-greeter/+bug/1568494) too to upstream.

Anyway, the two badges'll reach the upstream repo soon and all distros using Budgie with one of those greeters can benefit from it. :relaxed:

**Comment by IlyaBizyaev** [comment]
Wow, such a deep discussion for a 22x22 half-transparent image (^_^ ')
In my initial idea, Budgie could deliver this session icon in one of its packages in Ubuntu's BudgieRemix PPA. That would not affect SolusOS. And when the Ubuntu 16.10 is released, it will anyway have a different record in sources.list, so, it is possible not to include this icon for future versions - unity-greeter-budges package will ship it.

**Comment by HEXcube** [comment]
> In my initial idea, Budgie could deliver this session icon in one of its packages in Ubuntu's BudgieRemix PPA.

Yep, that's the plan! :relaxed: We already did that. The new `budgie-remix-lightdm-theme` package in Development PPA'll the Stable PPA soon and ship by default with budgie-remix 16.04.1 :smiley:

**Comment by IlyaBizyaev** [comment]
Great - that's the solution. Just didn't know that there's already a PR on Launchpad when designing this icon :)

**Comment by HEXcube** [comment]
Yeah, tracking both Launchpad and GitHub PRs can be hard sometimes :sweat_smile:

**Comment by IlyaBizyaev** [comment]
If there are no objections, marking this topic as closed?

**Comment by HEXcube** [comment]
> my concern is keeping the main vanilla Budgie Desktop, well, vanilla. Even Solus must abide by those rules and ensure customisations specific to our way of things is done properly - i.e. the budgie-desktop-branding package here on GH.

@ikeydoherty  Well, I think submissions of both logos to upstream was done properly. I mean, most distros and desktops submit their logos to those greeters instead of shipping them by their own.

But may I suggest something to prevent this confusion and duplication of effort in the future: a repo containing all the branding for Budgie desktop! :smiley: Not the current [Solus artwork repo](https://github.com/solus-project/artwork), but a separate one for Budgie desktop. Kinda like [Ubuntu GNOME's artwork repo](https://github.com/UbuntuGNOMEMarketing/ubuntu-gnome-artwork). We at budgie-remix are also building [a similar repo](https://github.com/budgie-remix/assets) but haven't reached that level yet. :smile:

Maybe add these to current [budgie-desktop-branding repo](https://github.com/solus-project/budgie-desktop-branding)? But I don't know if that fits well with the original purpose of that repo. :confused:
