### ISSUE TITLE
Gtk warnings about allocating size to GtkBox

### ISSUE THREAD

**Issue by TheAifam5** [solus-project/budgie-desktop#532]
ArchLinux
Budgie Desktop from GIT (master)

Budgie-Panel spamming:
```
(budgie-panel:13544): Gtk-WARNING **: Allocating size to GtkBox 0x21e4ba0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by ikeydoherty** [comment]
Yeah its GTK3.20's fault - pissing me off. Trying to find fixes for it outside of firing the whole GNOME stack out of the window and setting it on fire.

**Comment by nlaplante** [comment]
Each time it happens, the budgie session is killed and I'm back to the login screen. It can happen 3-4 times before I can actually login, This is after the huge update chunk in shannon.

**Comment by killkrt** [comment]
Hi,

Same problem here, tons of spamming warnings... Any solution yet?

P.S.:
I didn't find this issue so I created a new [one](https://github.com/solus-project/budgie-desktop/issues/545), so that's a duplicate, I'll ask to close it.

**Comment by ikeydoherty** [comment]
No solution no. I'm on a business trip in America- there's really very little I can do ..

**Comment by Zjemm** [comment]
Hi Ikey,

Have the same on arch with the budgie desktop. although everything seems to work fine, it's just spamming the journal.

let me know if you need some extra information/debug things 

anyway, love the budgie destop, maybe some day switch to solus, but it has to be as nice rolling as arch is :)

**Comment by ikeydoherty** [comment]
It's a GTK3.20 issue, there's no further information anyone can provide :)

**Comment by Zjemm** [comment]
Ok, no props :)

by the way, love your contributions on the JupiterBroadcasting shows. its how i found out about Solus

**Comment by ikeydoherty** [comment]
This is now fixed in git and will find its way into the next release.

**Comment by killkrt** [comment]
Sorry, I've just updated both GTK (version 3.22) and Budgie desktop (version 10.2.7-2) on Arch Linux and the issue seems to be still there (I've already made a reboot).

Any other feedback from other participants?

Thank you.

**Comment by fossfreedom** [comment]
@killkrt - you will need to contact your package maintainer to ensure this patch has been added - it hasn't yet:

 - https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/budgie-desktop

**Comment by worldwar345** [comment]
Solus was working well on my Dell i7559 for a few weeks since installing it, but now has intermittent freezing issues. It will completely freeze. Only solution is to hold down the power button to restart. I have restarted it quite a few times now and it seems to work okay sometimes and other times right after entering my password gets stuck with just the background image and cursor with nothing else showing on the screen, again requiring me to hold down the power button to turn off. I've really enjoyed using the OS and greatly appreciate all the hard work that has gone into making it... I know enough to duel boot and install Solus, but not enough to do what fossfreedom suggests if that will fix it. I'm happy to provide any info from my computer to help resolve the issue. Thank you in advance for any help.

**Comment by fossfreedom** [comment]
@worldwar345 doubtful freezing issues are budgie-desktop related.  Suggest use the Solus bug tracker rather than here - https://dev.solus-project.com/

**Comment by worldwar345** [comment]
Thank you for your help fossfreedom, I'll submit something there, or try to find my same issue.

**Comment by certainlysylvia** [comment]
Some time after this was patched now -- and just poking the thread because same is happening to me again now. Exact same message in journal -- on 4.13.13 current

Don't expect a quick fix and I know is likely upstream, just thought you might like to know :)

**Comment by TimoRiikonen** [comment]
Hello, could you give instructions for how to downgrade to a version that doesn't have this issue.
