### ISSUE TITLE
Pinned App Icons Change On Launch

### ISSUE THREAD

**Issue by Flat** [solus-project/budgie-desktop#540]
If using a theme the icons of pinned applications will change on launch to the default application icon as shown here.

Unlaunched:
![2016-08-16-00 51 49](https://cloud.githubusercontent.com/assets/2048861/17688279/d09a27c2-634b-11e6-9c70-14774e736100.png)

Launched:
![2016-08-16-00 52 04](https://cloud.githubusercontent.com/assets/2048861/17688285/dfa42966-634b-11e6-8809-bb0e616014d1.png)

**Comment by ikeydoherty** [comment]
That's the fault of the application overriding the icon, we just obey the X11 standards. If there is a *specific* application that you see should be prevented from overriding its icon (Which we've done in certain cases) - please open an issue for that specific icon/app use-case, and it'll get fixed. Right now this is expected behaviour.
