### ISSUE TITLE
app menu bar in window header

### ISSUE THREAD

**Issue by Gibbz** [solus-project/budgie-desktop#542]
I would love to see an option like ubuntu where the windows title contains the menu bar for the app. This saves screen space.
The window title is displayed, then when the mouse is hovered over the title bar, it switched to the menu bar.
A real saver for netbooks and low resolution devices!

**Comment by ikeydoherty** [comment]
Frankly the LIM is one of the most ridiculous things to have ever come out of Canonical.
It also "saves" roughly 8 pixels, and then wastes all of the titlebar space. GNOME applications don't really use menubars (extremely uncommon to see one) - they use a headerbar.

I don't really see it as warranted for Budgie, considering that Ubuntu and Mint patch applications to force menubars where they're no longer supposed to be..

Anyway, right now we don't have the power to even control something like that, as we use mutter, which has us extremely limited. I'll keep this open for _now_ because the core issue is that we lost all control of the WM anyway.

**Comment by ikeydoherty** [comment]
So I'm unable to add this to Mutter in anyway - sorry. In future, when we switch compositors, we'll re-evaluate this. Atm its out of my hands entirely..
