### ISSUE TITLE
Migrate to Wayland Display Server Protocol

### ISSUE THREAD

**Issue by DmitryHetman** [solus-project/budgie-desktop#553]
Xorg is deprecated, change protocol to Wayland instead.

**Comment by Ogromny** [comment]
From [TODO.md](https://github.com/solus-project/budgie-desktop/blob/master/TODO.md)
> Focus on X11 for now, even thinking about Wayland atm will make my head asplode.

**Comment by ikeydoherty** [comment]
Xorg is not deprecated, and Wayland isn't ready.

**Comment by ikeydoherty** [comment]
To fully adopt Wayland, Budgie will need to drop GTK in the UI, and Mutter in the WM.
As you can imagine that has some deep ramifications.

**Comment by Sunderland93** [comment]
Wayland is ready. GNOME 3.22 will use Wayland as default protocol. I don't understand why you can't do Wayland-session of Budgie, as is done with GNOME?

**Comment by ikeydoherty** [comment]
Yes GNOME will use it by default and all the X11-specific applications will suddenly disappear, including Chrome, Firefox, Steam, etc, and all drivers will suddenly support Wayland.. right?

Wayland takes away key things that Budgie *relies* on. Window placement? Completely down to the compositor. Reserved panel edges on the screen? No such thing. X11 specific. Concept of a panel? Complete bust. GNOME only does this because everything is *in process*. GNOME Shell uses a fork of Mx, Cogl, and Clutter, in tree, and these are all now entirely private APIs. None of that is available to downstream consumers of Mutter/GTK/etc. Many of these changes are the same ones that continue to shaft Budgie with each subsequent GNOME update.

Mutter also completely removed the ability to run GTK in process, meaning we can't even run budgie-panel inside budgie-wm, the mutter wrapper. Er go, without a rearchitecting of the project, Wayland isn't happening. It also means dropping mutter entirely because frankly the GNOME libs are the things limiting Budgie. Being a downstream of GNOME is almost intolerable. 

I understand you might be excited for Wayland, but know that it is *only* a protocol, and currently there are no practical benefits to defaulting to Wayland for us (Note we cannot even use GDM for Wayland support because GDM *requires* GNOME Shell (yay architecture.) and refuse to accept changes to permit alternative greeters).

When it is a suitable time to support Wayland, we will, and it won't be with Mutter, as I previously stated.

**Comment by ikeydoherty** [comment]
(The real discussion here should be about the replacements for Mutter, etc, which will happen in time in a separate conversation, but after more research on the matter, because there's no need for bikeshedding the issue to death ^^)

**Comment by mimi89999** [comment]
Gnome-shell and Mutter fully support Wayland now and many distributions decided to default to it. What are the issues preventing Budgie from adding Wayland support?
