### ISSUE TITLE
Open pinned applications sometimes creates a double icon effect

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#559]
As shown below, Spotify has 2 icons. The leftmost icon is pinned but is not show to be open while the right icon is shown to be open.
![screenshot from 2016-09-05 20-12-23](https://cloud.githubusercontent.com/assets/11936772/18259069/b250de7c-73a5-11e6-8505-d2ce5b0be3f6.png)

**Comment by ikeydoherty** [comment]
AFAIK this only happens with Spotify and yeah I can confirm this. It's down to a very poor design in the icon tasklist applet.

New Window Opens -> Spotify -> No WMCLASS -> New Button
Icon Changes -> Override
WMCLASS changes -> unhandled
Dangling Button

**Comment by tristan957** [comment]
I'll update you if I see it happen with other applications. Thanks for the quick response.

**Comment by ikeydoherty** [comment]
Wouldve got to it sooner but I fell asleep :D 

We need to fix these old design flaws which exist in Budgie, which is why I started a new `budgie-panel` repo to cleanroom this thing

**Comment by tristan957** [comment]
Ahh maybe you should get some sleep XD. Been working too hard my man

**Comment by mussel** [comment]
This issue is solved in the PR #551

**Comment by ikeydoherty** [comment]
Moved to next milestone as there is a big PR to check and it wont land in time for 10.2.7

**Comment by Mebur** [comment]
I have the same behavior with IntelliJ IDEA Community Edition.

**Comment by srcnalt** [comment]
Addition to this, RubyMine and Pycharm icons in Programming section, Godot icon in Games section are double in menu.
![screenshot from 2016-11-25 01-51-05](https://cloud.githubusercontent.com/assets/3163281/20611378/c3502070-b2b1-11e6-9291-3c10f257b01c.png)

**Comment by Cherkah** [comment]
same troubles with mutt & atom app

**Comment by ikeydoherty** [comment]
Different issues, guys.

**Comment by kotofond** [comment]
Same issue (technically could be different I guess) with PyCharm icon. I have it pinned to the panel and, when the PyCharm splash screen appears, it is shown as "active" but once the PyCharm's main window pops up the panel creates a new icon (duplicate) and makes it "active" instead of using the one that's pinned.

**Comment by Jacob-Vlijm** [comment]
Imo unlikely this has anything to do with Budgie specifically. Did you install pycharm locally or globally? Did you ever update to a newer version?

**Comment by kotofond** [comment]
@Jacob-Vlijm I installed it following the 3rd party repo instructions https://solus-project.com/articles/software/third-party/en/. I believe it means globally, not sure.
Yes, I did update it once using the same set of commands. The issue was present for both versions.
If it has nothing to do with Budgie then what else? Not pycharm itself apparently as there's no issue when I use it in Cinnamon or XFCE (both on Linux mint)

**Comment by Jacob-Vlijm** [comment]
This kind of errors could very well be caused by an additional or outdated version of a corresponding .desktop file in `~/.local/share/applications`. If installed globally, there could be a duplicate locally, or in case of updating, possibly the previous one still (also) exists in `/usr/share/applications`. On Ask Ubuntu, there are several similar issues described (not about Budgie).

**Comment by tristan957** [comment]
Can confirm that is not happening for me and the original spotify error @Jacob-Vlijm

**Comment by kotofond** [comment]
@Jacob-Vlijm Thanks for your response. I searched for `pycharm.desktop` across the entire file system and the only directories it was found in are:
![image](https://user-images.githubusercontent.com/17171725/28962869-6fe65020-794a-11e7-845e-5f262d236427.png)
Am I missing something? By the way I experience absolutely the same issue with WebStorm. In addition to that, to collect more data I just installed PhpStorm and Spotify (never used them my life before) and the issue occurs for them too.
