### ISSUE TITLE
Gnome Terminal's Appmenu is shown, but doesn't work

### ISSUE THREAD

**Issue by junrrein** [solus-project/budgie-desktop#582]
When running gnome-terminal under Budgie, gnome-terminal's appmenu button is shown, but upon clicking it, nothing happens.

It works fine under Gnome.

The Gtk theme used doesn't make a difference.

Here's a video showing the issue under Budgie:
https://vid.me/Favo

Here's a video showing the normal gnome-terminal behavior under Gnome:
https://vid.me/64jR

This issue makes accessing Gnome Terminal's preferences impossible.

Using:
Opensuse Tumbleweed
gnome-terminal                        3.20.2
budgie-desktop                         10.2.7

**Comment by ikeydoherty** [comment]
Menu -> Edit -> Preferences, you mean that? Budgie doesn't support or use AppMenu, which is a GNOME-only spec.

Can you not enforce your menubar to show? i.e. right click the terminal and select Show Menubar

**Comment by junrrein** [comment]
Sorry, I was wrong about preferences being inaccesible, since I'm used to hiding gnome-terminal's menubar.

But saying that Budgie doesn't support or use AppMenu is kind of unconvincing, since AppMenus are needed in other applications that Solus uses by default, such as Nautilus, as show in the following screenshot:

![captura de pantalla de 2016-09-12 19-14-58](https://cloud.githubusercontent.com/assets/962049/18454881/42191f02-791d-11e6-99bf-1e1633b174f7.png)

I don't think you can access Nautilus' preferences window without using its AppMenu.

**Comment by ikeydoherty** [comment]
Budgie isn't displaying that, GTK is. We tell GTK we don't support the notion of the AppMenu (part of #261 is supporting this on other distros outside of Solus) - and then GTK displays a fallback AppMenu in the CSD.  GNOME Terminal doesn't use CSD, so GTK is unable to display the fallback. I'd argue this is more of a limitation in GNOME Terminal, in that it doesn't correctly support being run outside of GNOME Shell. It's a trivial enough fix, too.

**Comment by junrrein** [comment]
Thanks for the information, it really clarified the issue for me. It seems that, when running under Gnome, gnome-terminal's appmenu-in-titlebar is drawn by gnome-shell, not Gtk. I now have all the info I need to file a bug against gnome-terminal.

Thanks and have good day!

**Comment by ikeydoherty** [comment]
Thanks, and thanks *even more* for escalating this upstream with GNOME. Nice to see that :D 

Also enjoy your day, ty ! :)

**Comment by junrrein** [comment]
Here's a link to the bug report, in case you are interested to follow the issue:
https://bugzilla.gnome.org/show_bug.cgi?id=771330

**Comment by junrrein** [comment]
A gnome-shell developer replied promptly, explaining that he can do nothing to fix the issue, since when an AppMenu is  drawn in a traditional titlebar, it's the environment the one which needs to render the menu, since it can't be done by Gtk.

The link to the relevant comment is the following:
https://bugzilla.gnome.org/show_bug.cgi?id=771330#c3

Could you reconsider supporting AppMenus inside Budgie?

**Comment by ikeydoherty** [comment]
Its not a Budgie or a Mutter issue. Firstly, GTK shouldn't exhibit GNOME Shell specific behaviour as it's a cross-platform toolkit, but we can argue about that until the cows come home and the GNOME people wouldn't agree with it, and frankly I don't really blame them.

Secondly, GNOME Terminal is the thing acting derpy. Note how other apps work ok. It doesn't use CSD yet it uses AppMenu, therefore GNOME Terminal is *non-portable* outside of GNOME Shell, unless forced to use CSD internally which only happens when using Wayland. If GNOME choose to implement a HIG and their own "standards" by way of AppMenu, then they should ensure their applications actually obey them, to the letter, permitting the fallback path. In this case it means using CSD.

**Comment by junrrein** [comment]
Thanks for explaining the issue further. The next step will be filing a bug against gnome-terminal asking for them to use CSD inside X to draw their titlebar, which would solve the issue.

Cheers!

**Comment by ikeydoherty** [comment]
If GNOME upstream is unresponsive we'll find some kind of hack..

**Comment by junrrein** [comment]
I don't expect upstream to be unresponsive, I just hope to get the response we are looking for.

Here's the new bug report:
https://bugzilla.gnome.org/show_bug.cgi?id=771333

**Comment by junrrein** [comment]
See the comment from a gnome-terminal developer on that bug report:
https://bugzilla.gnome.org/show_bug.cgi?id=771333#c2

I think that the way forward is for budgie-wm to not show an AppMenu on any server-side decorated window.

**Comment by junrrein** [comment]
I forgot to add: The application provides a fallback for not having an AppMenu by replicating all of its functionality in its normal menues. Any and all applications that use AppMenus should provide some kind of fallback. This is not a Budgie issue.

**Comment by ikeydoherty** [comment]
Budgie WM uses *Mutter*, who have claimed they're not responsible, for the bug in GNOME Terminal, who don't obey their own HIG, so they're not responsible.

I'm not supporting GNOME's AppMenu in Budgie. And *clearly* GNOME will only suit GNOME - as can be seen with those reports. I'd rather kick Mutter and the other GNOME code out of Budgie altogether.

**Comment by ikeydoherty** [comment]
Note to anyone reading: Dropping mutter is already a roadmap item, as is dropping some highly specialised components .. There are areas where we "cheat" to gain compatibility, and where we suffer. As seen above..

**Comment by junrrein** [comment]
When I posted this issue (with a lot of wrong assumptions) I didn't intend to start a finger-pointing blame game, and neither to give you a spike in blood pressure.

After all, this issue is really minor. There is no loss of functionality at all and, AFAIK, only gnome-terminal is hit by this issue so any effort spent on it won't be worth it.

Here, have a red panda for your troubles.

![](http://media.salon.com/2015/08/shutterstock_51111274.jpg)

Thanks for taking time out of your schedule to reply so promptly and, of course, for all the work put into Budgie.

**Comment by ikeydoherty** [comment]
You misunderstand me :P There is no blood pressure involved, note that the last comment I made was to clear up any confusion surrounding existing plans. Budgie is in a delicate spot because simply it does *too much* to be GNOME compatible, which can backfire.

This is a perfect case of that. If GNOME Terminal were to use CSD, the issue would have never appeared. Budgie doesn't support AppMenu. Through using Mutter, we end up with the AppMenu button that we're unable to control, because we also need that in CSD windows.

It's not a blame game, if anything it's a very amusing loop that demonstrates how quickly one can shoot themselves in the foot. In our case, this only demonstrates that we used a shotgun. :P 
I harbour no ill will against GNOME for this, really isn't their problem _from their perspective_.
We also know the issue will go away eventually when we swap out Mutter.
