### ISSUE TITLE
[Feature request] Budgie Panel additional customization

### ISSUE THREAD

**Issue by yarpus** [solus-project/budgie-desktop#617]
**Operating System**:Solus 1.2.0.5 64-bit
**Budgie version**: 10.2.7

**Feature**
These features are based on features that are found among other panels (from different DEs) as common.
- Transparency
- Vertical panels
- 'Text-only' display of Budgie Menu (currently you can choose icon-only or both)
- Returning to default panel's configuration

**Comment by Solarunit** [comment]
> Transparency
> Returning to default panel's configuration

+1

**Comment by moriel5** [comment]
+2

**Comment by JoshStrobl** [comment]
- Transparency option has since been added
- Vertical panels have since been made a thing
- You can remove the name of the icon and have the menu label for "text only"
- No immediate plans on a default panel configuration / restoration option in Budgie Desktop Settings but you can do `--reset` on `budgie-panel` and it'll reset it entirely.
