### ISSUE TITLE
Inability to move icons on Icons Task List

### ISSUE THREAD

**Issue by yarpus** [solus-project/budgie-desktop#620]
Operating System:Solus 1.2.0.5 64-bit
Budgie version: 10.2.7

The issue encountered
It is not possible to grab any of the icons in task list to actually change their order. No matter how you try to do it, you end up launching the application.
Either holding mouse button is registered as click or there's no proper behavior for holding mouse button.

Steps to reproduce the issue
Try to move icons residing on the taskbar.
Behavior is the same for apps that are pinned/not-pinned and launched/not-launched.

**Comment by fossfreedom** [comment]
This is already on the TODO list - https://github.com/solus-project/budgie-desktop/blob/master/TODO.md

**Comment by ikeydoherty** [comment]
Implemented in git, will land in `10.2.8`

**Comment by ckrzen** [comment]
Great work fella's!

budgie-desktop will become my defacto end-user desktop deployment in Ubuntu 16.04 & 16.10 going forward as _the_ alternative to Unity-7. budgie-desktop is simply the best Windows-10-like(configurable) skid-slicker for transitioning users to Linux without all of the additional dependencies inherent to XFCE4, LXDE(QT) or their alternate-spins(Xubu/Lubu) while still maintaining all of the GTK3 goodness and Gnome apps. It's lighter-weight than gnome-session-flashback and more attractive.


*** FEATURE-REQUEST ***

Please expose a setting in either Raven or gsettings to _lock_ the "Icon Tasklist" icons as this is a _feature_ to me in order to deploy and maintain consistent user interfaces and prevent the occasional _sticky-finger_ on mouse button which drags an icon off-of or around the "Tasklist".


SEE:

org.gnome.gnome-panel.lockdown 

`  <schema path="/org/gnome/gnome-panel/lockdown/" id="org.gnome.gnome-panel.lockdown">

    <key type="b" name="locked-down">

      <default>false</default>

      <summary>Complete panel lockdown</summary>

      <description>If true, the panel will not allow any changes to the configuration of the panel. Individual applets may need to be locked down separately however. The panel must be restarted for this to take effect.</description>

    </key>
`


AND:

https://help.gnome.org/admin/deployment-guide/


Thank you for your consideration of these sys-admin features!

**Comment by ikeydoherty** [comment]
Hi - please file this as a separate issue otherwise it won't be tracked (This is on a dead closed issue :))
