### ISSUE TITLE
[Feature Request] Shortcut to clear notifications

### ISSUE THREAD

**Issue by imdyske** [solus-project/budgie-desktop#709]
In order to clear notifications, user has to click a button in raven. It gets a bit annoying to always use a mouse especially when shortcut for viewing notifications exists <kbd>Super</kbd>+<kbd>N</kbd> *(by default)*. Therefore it would be beneficial to have a way to clear them using keyboard only.

**Comment by hersh-verthun** [comment]
I second that.

**Comment by ikeydoherty** [comment]
Happy to implement it but y'all need to decide on what that shortcut is :)

**Comment by imdyske** [comment]
Well, since there are shortcuts for <kbd>N</kbd>otifications and <kbd>A</kbd>pplets it would make sense for it to be <kbd>Super</kbd>+<kbd>C</kbd>lear. :smile:

**Comment by ikeydoherty** [comment]
So, I read this from the frontpage and it didn't show that you markdown ticked `C`, so I'm already thinking, "what the fuck is a Super+Clear button...." before I got here xD

**Comment by imdyske** [comment]
Super+Clear could execute `sudo rm -rf /` as a test for pure statelessness xD

**Comment by tristan957** [comment]
Yea I'm good with Super+C

**Comment by Vistaus** [comment]
I want this as well! I don't really care what shortcut it'll be, I'll probably change it anyway (using dconf-editor) ;)

**Comment by UnlawfulMonad** [comment]
I'm working on this. Currently assuming `<Super>C` for the shortcut but it's easy to change. I'll be submitting a PR soon.

**Comment by UnlawfulMonad** [comment]
Copy pasting my question from my duplicate issue:

I've been trying to add a key binding (<Super>C) to call NotificationsView.clear_all. Currently I've hooked up the keybinding but I can't find a path between BudgieWM (where the keybinding is received) and NotificationsView which seems to only be accessible as a dbus interface (org.freedesktop.Notifications). There doesn't seem to be any way to do this from either Raven or RavenIface. Since there's no way to get a list of notification IDs I would propose having NotificationsView be a simple wrapper (to keep implementing org.freedesktop.Notifications) around a new class where this functionality is exposed as a new dbus interface with a ClearAll method.

@ikeydoherty Is this an okay way to go about this?
