### ISSUE TITLE
Panel - Icon Task List Visual Issue

### ISSUE THREAD

**Issue by krisgopal128** [solus-project/budgie-desktop#739]
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8

**The issue encountered**
Icon Task List goes beyond End Spacer
![screenshot from 2016-11-23 23-41-29](https://cloud.githubusercontent.com/assets/13931326/20576255/abf88f38-b1d6-11e6-9f1b-c6aaa0fec059.png)

 ...

**Steps to reproduce the issue**
Open File Manager 40-50 Times 

 ...

**Comment by Vistaus** [comment]
My dad has the same problem with the Task List (the non-icon one). So I think it's a generic Budgie issue. Hope it gets solved though!

**Comment by JoshStrobl** [comment]
The issue with the Tasklist has been resolved in git. For the IconTasklist, Icon Grouping for applications is a thing so that is the supported path going forward. I may re-evaluate this in the future and add a similar implementation, so long as it doesn't conflict with the functionality of scroll up / down on IconButtons for switching and/or maximize/minimize.
