### ISSUE TITLE
Cleaning up the Menu

### ISSUE THREAD

**Issue by Krutonium** [solus-project/budgie-desktop#789]
**Operating System**: Arch Linux
**Budgie version**: Latest Release, and latest build from Git.

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

    budgie-desktop 10.2.9

**The issue encountered**

I have menu entries in the "Start Button" (Dunno what else to call it) that are simply empty, or contains applications I don't want listed; is there a simple way to remove them? I've tried an application called Meow, but that didn't work in the slightest, as well as Alacarte. Any input would be greatly appreciated.Iss
![issue_start](https://cloud.githubusercontent.com/assets/3945538/22596945/990b26bc-e9fb-11e6-8a03-fdb64dc07acc.png)

(Ignore the kitty)

That plus 3 others are all like that.
 ...

**Comment by fossfreedom** [comment]
On Ubuntu Budgie we use menulibre - hope that helps https://launchpad.net/menulibre

**Comment by PFCKrutonium** [comment]
Unfortunatly, upon trying that, I get this error :/

```
[krutonium@HpArch ~]$ menulibre
Traceback (most recent call last):
  File "/usr/bin/menulibre", line 40, in <module>
    import menulibre
ModuleNotFoundError: No module named 'menulibre'
```

**Comment by PFCKrutonium** [comment]
Aha! I had some luck with an application called ezame - A bit of a confusing interface, but it did the job!

**Comment by ikeydoherty** [comment]
Moral of the story being Budgie Menu is kinda stupid and shouldn't add empty menu categories..?

**Comment by PFCKrutonium** [comment]
To be fair, they did previously contain stuff. Honestly, I'd prefer if Budgie had a built in utility to re-organize stuff (Or even Drag and Drop to move stuff around the menu? Some sort of Edit mode?)

**Comment by jawz101** [comment]
An editable menu is one of my top desires in a desktop and for some reason most Linux desktops don't include an easy option.

I assume a searchable menu relies on each app to have multiple tags associated with them so users unfamiliar with Linux or a specific distro's application suite to allow for common programs to appear (e.g. a Windows user would expect to find a word editor if they search for "Word" or "notepad".)

I saw a Ubuntu video a while ago showing off the Unity Desktop and how easy it was to find your apps by typing a search for them.  Really?  On a touch-friendly ui?  If you have 100's of apps that means you have to know each apps name and what you want to find whereas a user-controlled menu structure means a user could organize 100's of apps in a way that any app can be found within a few clicks.

When Gnome Desktop was revamped for GTK 3 they started a bad trend with unorganized menus.  Ubuntu carried the tradition along in Unity's lenses/scopes/whatever they're called.  Gnome Desktop has long supported folder creation via config files however they never implemented a gui method or drag and drop way of creating them.  Like, it's been a deal breaker for me on any desktop so I've stuck with MATE, Cinnamon, or XFCE because at least they have a built-in menu editor or the clunky MenuLibre.

It bugs me on most desktops that if I install any KDE apps on any distro I suddenly have a bunch of QT developer tool icons in my menu.  I'm an end user- why would I care about some random QT developer console and cmake or whatever in my menus?

Sorry, I just needed a place to get this out of my system.  But yeah, an application menu I can edit makes a world of difference.  If I handed a Windows or Mac user a Linux laptop and a bunch of random QT development and debugging apps are suddenly in their menu because I installed a KDE app they'd say "woah, this is too technical for me."  It just kills the experience.

**Comment by PFCKrutonium** [comment]
I think, I am going to re-open this, since this is a feature request at this point, and is still an issue.

**Comment by ikeydoherty** [comment]
Where is the feature request? The fix was given to use `libremenu` to edit the menu

**Comment by PFCKrutonium** [comment]
I would prefer something built in tbh. (Sorry I took a while to respond)

At the very least it should not display empty entries.

**Comment by jawz101** [comment]
+1  I think it's silly when I install a QT app and suddenly I have all of these menu items for developer tools, cmake, all of this random stuff that I is clutter for an end user.  The [menulibre](https://smdavis.us/projects/menulibre/), [alacarte](http://ftp.gnome.org/pub/GNOME/sources/alacarte/3.11/), [Meow](http://pnmougel.github.io/meow/), [Gnome AppFolders Manager](http://www.muflone.com/en/gnome-appfolders-manager/index) are all great but I'd hope a desktop would actually offer to edit its own menus.

If a web browser didn't let me organize my bookmarks I'd get annoyed just as much.

**Comment by ikeydoherty** [comment]
This goes a bit beyond bookmarks as it isnt its "own menus", we're talking about system wide menus, and as such pre-existing menu editors should be used to edit those. Standard tools..

**Comment by jawz101** [comment]
No worries, Ikey.  I just wanted to express the sentiment.  It's more of a general desktop opinion anyways.  Especially with Gnome since they support folders but instruct the user to edit config files to make them.  That just seems like an incomplete feature.

Love Late Night Linux and your guest appearances on LUP.

**Comment by ikeydoherty** [comment]
Yea I was barely awake when I wrote that sorry :P

**Comment by jawz101** [comment]
I'm always barely awake

**Comment by PFCKrutonium** [comment]
We all do it ;P

**Comment by mohdsalmanshaikh63** [comment]
Newbie linux user here. I am loving the new 17.10 budgie. Just noticed this bug. I tried menuLibre still no luck and also sometimes duplicate entries are also created in plank for example **Files** is being repeated in plank. That aside, any solution to these duplicate menu entries?

**Comment by mohdsalmanshaikh63** [comment]
Newbie linux user here. I am loving the new 17.10 budgie. Just noticed this bug. I tried menuLibre still no luck and also sometimes duplicate entries are also created in plank for example **Files** is being repeated in plank. That aside, any solution to these duplicate menu entries?

**Comment by EmberQuill** [comment]
menuLibre creates duplicates all over the place (duplicate categories, duplicate apps, extra empty categories, duplicate .desktop files in ~/.local/applications, etc.), alacarte's automatic naming convention for new .desktop files is ridiculous , and Meow and Gnome App Folders Manager both only show like 2 of the 16 folders in my menu. Is there any menu management application that actually works or will I have to edit the .desktop and .menu files manually?

**Comment by mindinsomnia** [comment]
Yeah a built in menu editor would be amazing. :v

**Comment by locomot1f** [comment]
I did find this -- https://www.omgubuntu.co.uk/2018/02/app-menu-editor-for-ubuntu-appeditor

gonna give it a try

**Comment by Krutonium** [comment]
@locomot1f Any luck? I'm in this boat *again*.

**Comment by locomot1f** [comment]
i ended up going back to menulibre, and some editing of the menu file

**Comment by JoshStrobl** [comment]
I'm going to be closing this issue.

1. Budgie Menu should no longer be adding duplicate desktop item entries so long as the IDs are the same, per 07a76a0c5f3c6b5f2a9c5ce95aa06c92a74d7a57
2. Budgie Menu will no longer add category buttons for categories which are empty as of 57b6663c2c77001bd2b79110ab75d731961f1a9b

Any extraneous features like a menu editor, to modify or hide installed applications, is IMO out of scope for Budgie and is already handled well by existing third-party tools.

**Comment by Krutonium** [comment]
>already handled well by existing third-party tools.

What tools? I have yet to find on that can competently handle the task.

**Comment by Ryland0** [comment]
If anyone is still interested, this works great.

https://github.com/donadigo/appeditor

**Comment by Higherselfhiphop** [comment]
Ya... Budgie desktop have great potential... Yet the menu issues are ridiculous......  I've been trying to locate where the menu info even is.... Giving up on Budgie, due to the menu issues....

**Comment by mgrouch** [comment]
I have overrides for menu structure in
~/.config/menu/gnome-applucations.menu

alacarte shows menu structure respecting it. 

However budgie menu totally ignores it
